dashboard/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
                       url(r'^$', 'dashboard.views.dashboard', name='dashboard'),
                       url(r'^update_profile$', 'dashboard.views.update_profile', name='update_profile'),
                       url(r'^download_order_file/(?P<order_id>\d+)/$','dashboard.views.download_order_file', name='download_order_file'),
                       )

eprint/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'eprint.views.home', name='home'),
                       url(r'^register$', 'eprint.views.register', name='register'),
                       url(r'^login$', 'eprint.views.user_login', name='user_login'),
                       url(r'^contact$', 'eprint.views.contact', name='contact'),
                       url(r'^logout$', 'eprint.views.user_logout', name='user_logout'),

                       url(r'^dashboard/', include('dashboard.urls')),

                       url(r'^trial_order$', 'order.views.trial_order', name='trial_order'),
                       url(r'^print_order$', 'order.views.print_order', name='print_order'),
                       url(r'^backend/', include('backend.urls')),

                       url(r'^admin_xxxx/', include(admin.site.urls)),
                       )

order/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       )

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
# Create your models here.


class BuildingGroup(models.Model):
    name = models.CharField(max_length=20)


class Building(models.Model):
    group = models.ForeignKey(BuildingGroup)
    name = models.CharField(max_length=20)


def get_grouped_buildings():
    return BuildingGroup.objects.all()


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=9)
    phone_number = models.CharField(max_length=20)
    building = models.ForeignKey(Building)
    gender = models.IntegerField()
    number = models.CharField(max_length=15)

    def can_use(self):
        if self.phone_number:
            return True
        else:
            return False


admin.site.register(BuildingGroup)
admin.site.register(Building)

dashboard/views.py
# -*- coding=utf-8 -*-
# Create your views here.
from django.shortcuts import render_to_response, render_to_response
from django.shortcuts import HttpResponse, HttpResponseRedirect, RequestContext
from dashboard.models import UserProfile, Building
from order.models import PrintOrder
from eprint import validate
from eprint.views import authenticated_view
from dashboard.models import get_grouped_buildings
from django.core.servers.basehttp import FileWrapper
import os


def get_profile_of_user(user):
    try:
        user_profile = UserProfile.objects.get(user=user)
    except:
        user_profile = None
    return user_profile


def get_user_print_orders(user):
    return PrintOrder.objects.filter(user=user).order_by('time').reverse()


@authenticated_view
def dashboard(request):
    user = request.user
    user_profile = get_profile_of_user(user)
    if not user_profile:
        user_profile = {}
    context = RequestContext(request)
    context['user_profile'] = user_profile
    context['groups'] = get_grouped_buildings()
    context['orders'] = get_user_print_orders(user)
    return render_to_response('dashboard.html', context)


def validate_user_profile(user_profile):
    if validate.update_profile_validate['name'](user_profile.name) \
            and validate.update_profile_validate['phone'](user_profile.phone_number) \
            and validate.update_profile_validate['student_number'](user_profile.number) \
            and validate.update_profile_validate['building'](user_profile.building) \
            and validate.update_profile_validate['gender'](user_profile.gender):
        return True
    return False


@authenticated_view
def update_profile(request):
    user = request.user
    name = request.GET['name']
    phone = request.GET['phone']
    student_number = request.GET['student_number']
    building_id = request.GET['building']
    building = Building.objects.get(id=building_id)
    gender = request.GET['gender']

    user_profile = get_profile_of_user(user)
    if not user_profile:
        user_profile = UserProfile()
        user_profile.user = user
    user_profile.name = name
    user_profile.phone_number = phone
    user_profile.building = building
    user_profile.gender = gender
    user_profile.number = student_number

    if validate_user_profile(user_profile):
        user_profile.save()
        return HttpResponseRedirect('/dashboard')
    else:
        # TODO: show error message here
        return HttpResponseRedirect('/dashboard')


def get_order_of(user, id):
    try:
        order = PrintOrder.objects.get(user=user,id=id)
    except:
        order = None
    return order


def download_file_response(path):
    wrapper = FileWrapper(file(str(path), 'rb'))
    response = HttpResponse(wrapper, content_type='application/octet-stream')
    response['Content-Length'] = os.path.getsize(str(path))
    response['Content-Encoding'] = 'utf-8'
    response['Content-Disposition'] = 'attachment;filename=%s' % path.split('/')[-1]
    return response


@authenticated_view
def download_order_file(request, order_id):
    order = get_order_of(request.user, order_id)
    if not order:
        return HttpResponseRedirect('/dashboard')

    return download_file_response(str(order.up_file))

templates/admin_index.html
{% extends 'base.html' %}
{% block custom_css %}
    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 350px;
            margin: 20px auto 20px auto;
            width: 460px;
        }
        .register-wrapper {
            width: 250px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 30px;
        }
        .register-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width: 250px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}
          <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
              </button>
              <a class="navbar-brand" href="#">All Orders:</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-01">
              <ul class="nav navbar-nav navbar-left">
                <li><a href="trial_orders_list">TrialOrders</a></li>

                <li><a href="print_orders_list">PrintOrders</a></li>
               </ul>
            </div><!-- /.navbar-collapse -->
          </nav><!-- /navbar -->




{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
    $(function(){
        $("select").select2({dropdownCssClass: 'dropdown-inverse'});
    });
</script>
{% endblock %}

templates/admin_index_print_orders.html
{% extends 'base.html' %}
{% block custom_css %}
    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 350px;
            margin: 20px auto 20px auto;
            width: 460px;
        }

        .register-wrapper {
            width: 250px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 30px;
        }

        .register-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width: 250px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}


    <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="#">All Orders:</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-01">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="trial_orders_list">TrialOrders</a></li>

                <li><a href="print_orders_list">PrintOrders</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav><!-- /navbar -->


    <div style="color:#0f0918">
        this is printorders list.
        <br>
        {% for order in orders_list %}
            {{ order.user.email }} &nbsp;&nbsp;{{ order.up_file }} &nbsp;&nbsp;{{ order.time }} &nbsp;&nbsp;
            {{ order.status }} &nbsp;&nbsp;{{ order.color }}
            &nbsp;&nbsp;{{ order.method }} &nbsp;&nbsp;{{ order.tel }}
            <form action="download_files/{{ order.up_file }}" method="post" target="_blank">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit"  name="btn" value="{{ order.up_file }}">download file</button>
            </form>
            <br>
        {% endfor %}


    </div>


{% endblock %}

{% block custom_javascript %}
    <script type="text/javascript">
        $(function () {
            $("select").select2({dropdownCssClass: 'dropdown-inverse'});
        });
    </script>
{% endblock %}

templates/admin_index_trial_orders.html
{% extends 'base.html' %}
{% block custom_css %}
    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 350px;
            margin: 20px auto 20px auto;
            width: 460px;
        }
        .register-wrapper {
            width: 250px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 30px;
        }
        .register-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width: 250px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}
          <nav class="navbar navbar-inverse navbar-embossed" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                <span class="sr-only">Toggle navigation</span>
              </button>
              <a class="navbar-brand" href="#">All Orders:</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-01">
              <ul class="nav navbar-nav navbar-left">
                <li><a href="trial_orders_list">TrialOrders</a></li>

                <li><a href="print_orders_list">PrintOrders</a></li>
               </ul>
            </div><!-- /.navbar-collapse -->
          </nav><!-- /navbar -->

          <div style="color:#0f0918">
                this is trialorders list.
                <br>
                {% for order in trial_orders_list %}
                    {{ order.name }} &nbsp;&nbsp;{{ order.phone }} &nbsp;&nbsp;{{ order.file }} &nbsp;&nbsp;{{ order.building }} &nbsp;&nbsp;{{ order.status }}
                     <form action="download_files/{{ order.file }}" method="post" target="_blank">
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit"  name="btn" value="{{ order.up_file }}">download file</button>
                    </form>
                    <br>
                {% endfor %}
            </div>

{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
    $(function(){
        $("select").select2({dropdownCssClass: 'dropdown-inverse'});
    });
</script>
{% endblock %}

templates/admin_login.html
{% extends 'base.html' %}

{% block custom_css %}
    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 350px;
            margin: 20px auto 20px auto;
            width: 460px;
        }
        .register-wrapper {
            width: 250px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 30px;
        }
        .register-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width: 250px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="wrapper">
        <div class="register-wrapper">
            <h3>管理员登陆</h3>
            <form class="form-group register-form" method="POST" action="/backend/api/login">
                {% csrf_token %}
                <input type="text" name="email" placeholder="邮箱" class="form-control" />
                <input type="password" name="password" placeholder="密码" class="form-control" />
                <input type="submit" value="登陆" class="btn btn-embossed btn-primary"
                    style="width:230px;background-color:#19bb9b;" />
            </form>
        </div>
    </div>
    <!-- /.wrapper-->
</div>
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
    $(function(){
        $("select").select2({dropdownCssClass: 'dropdown-inverse'});
    });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <title>
{% block title %}
    E Print
{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Loading Bootstrap -->
    <link href="/static/css/vendor/bootstrap.min.css" rel="stylesheet">
    <!-- Loading Flat UI -->
    <link href="/static/css/flat-ui.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link rel="stylesheet" type="text/css" href="/static/css/page-frame.css">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->

{% block custom_css %}

{% endblock %}
  </head>

  <body>
    <div class="navbar-container">
        <nav class="navbar navbar-inverse navbar-lg" role="navigation">
        	<a class="navbar-brand" href="/">E Print</a>
{% block navbar %}
            {% if user.username %}
                <div class="navbar-form navbar-right">
                <a href="/dashboard" style="padding-left: 20px; padding-right: 20px;">{{ user.username }}</a>
                <a href="/logout"  style="padding-left: 20px; padding-right: 20px;">退出</a>
                </div>
            {% else %}
            <!-- Navbar content -->
            <form class="navbar-form navbar-right" action="/login" method="POST" id="user-form">
                {% csrf_token %}
                <input name='email'type="text" placeholder="邮箱" class="form-control" />
                <input name='password' type="password" placeholder="密码" class="form-control" />
                <input type="submit" value="登录" class="btn btn-default navbar-btn" style="width:120px;" />
                <a href="/register" style="padding-left: 20px; padding-right: 20px;">注册</a>
            </form>
            {% endif %}
{% endblock %}
		</nav>
        <!-- /.navbar-->
    </div>
{% block content %}		
{% endblock %}

{% block footer %}
	<div class="navbar-fixed-bottom footer" >
		<div class="footer-wrapper">
            <a href="/contact">联系我们</a>
            <!--<p style="color:#fff">@hackeris</p>-->
        </div>
	</div>
{% endblock %}

    <!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
    <script src="/static/js/vendor/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/js/vendor/video.js"></script>
    <script src="/static/js/flat-ui.min.js"></script>
{% block custom_javascript %}
    <script type="text/javascript">
    </script>
{% endblock %}

  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block custom_css %}
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" >
{% endblock %}

{% block content %}
<ul class="sidebar hide-on-tablets" id="sidebar">
	<h6 style="color: #fff;">个人中心</h6>
	<p style="color: #fff;">{{user.email}}</p>
	<li><a href="#user-info" id="to-user-info">个人信息</a></li>
	<li><a href="#my-print" id="to-my-print">我的打印</a></li>
</ul> <!-- /nav -->

<div class="container" style="color: #fff;">

{% include 'user_info.html' %}
	
{% include 'my_print.html' %}

</div>
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
	$("select").select2({dropdownCssClass: 'dropdown-inverse'});
	$(':radio').radiocheck();
    $('#black-white').radiocheck('check');
    $('#paid').radiocheck('check');

	$('#to-user-info').click(function(){
		$('#my-print').css('display','none');
		$('#user-info').css('display','block');
	});
	$('#to-my-print').click(function(){
		$('#my-print').css('display','block');
		$('#user-info').css('display','none');
	});
    $(function () {
        $('[data-toggle=tooltip]').tooltip();
    });
    {% if user_profile.gender == 1 %}
    	$('#boy').radiocheck('check');
    {% elif user_profile.gender == 0 %}
    	$('#girl').radiocheck('check');
    {% endif %}
    $('#build-select').val({{user_profile.building.id}})
</script>
{%  endblock %}

templates/index.html
{% extends 'base.html' %}

{% block custom_css %}

    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 250px;
            margin: 0px auto 20px auto;
            width: 960px;
        }
        .wrapper-content {
            width: 840px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 40px;
        }
        #red-wrapper {
            height: 200px;
        }
        #try-wrapper {
            height: 480px;
        }
        #try-wrapper > div {
            height: 480px;
            width: 320px;
        }
        .try-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width:320px;
            color:#fff;
        }
        #free {
            float: left;
            width: 50%;
            height: 100%;
            padding-right: 20px;
        }
        #paid {
            float: right;
            width: 50%;
            height: 100%;
            padding-left: 20px;
        }
        #paid > p, #free > p {
            font-size: 16px;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">

    <div class="wrapper" id="top-wrapper">
        <div class="wrapper-content" style="height: 250px; padding-top: 0px;">
            <div id="free" style="padding-top: 20px;">
                <h6>免费打印</h6>
                <p>我们提供免费的打印服务，but，我们也会在免费打印的文档中嵌入一些广告</p>
                <p>适用于一些不那么正式的文档，比如打印点开卷考试参考资料啥的</p>
            </div>
            <div id="paid" style="padding-top: 20px;">
                <h6>付费打印</h6>
                <p>付费的打印就像平时所使用的打印服务一样，我们尽可能保证打印后的效果与原文档一致</p>
                <p>适用于正式文档，如论文、实验报告</p>
                <p>还可以彩印哦</p>
            </div>
        </div>
    </div>
    <!-- /.wrapper-->

    <div class="wrapper" id="red-wrapper">
        <div class="wrapper-content">
        {% if user.username %}
            <p>点击进入<a class="btn btn btn-danger" style="margin: 0 10px;" href="/dashboard">个人中心</a>即可开始上传文件打印</p>
        {% else %}
            <p>直接点击<a id="try" class="btn btn btn-danger" style="margin: 0 10px;" href="#">我要打印</a>即可开始上传文件打印</p>
        {% endif %}
            <p style="font-size: 10px;color: #16a085;">别问我为什么这个按钮是红色的，反正你已经看到了</p>
        </div>
    </div>
    <!-- /.wrapper-->

    <div class="wrapper" id="try-wrapper" style="display: none;">
        <div class="wrapper-content">
            <p style="font-size: 10px;color: #16a085;">未注册的用户可以打印一次试试，注册后可以彩印，还可以有免费打印的方式可选</p>
            <form class="form-group try-form" enctype="multipart/form-data"  method="POST" action="trial_order">
                {% csrf_token %}
                <input type="text" name="name" placeholder="怎么称呼？" class="form-control" />
                <input type="text" name="phone" placeholder="留个电话方便我们联系您" class="form-control" />

                <!-- Building select -->
                <select class="form-control select select-primary select-block mbl" id="build-select" name="building">
                    <option value="100">选择宿舍以便于我们配送</option>
                    <optgroup label="本科1组团">
                        <option value="0">1栋</option>
                        <option value="1">2栋</option>
                    </optgroup>
                    <optgroup label="本科2组团">
                        <option value="2">x栋</option>
                        <option value="3">x栋</option>
                        <option value="4">x栋</option>
                    </optgroup>
                </select>

                <input type="file" id="print-file" name="file" class="btn btn-embossed btn-primary"/>

                <input id="submit" type="submit" value="打印" class="btn btn-embossed btn-primary"
                    style="width:230px;background-color:#19bb9b;" />
                <input id="btn-cancel" type="button" value="取消" class="btn btn-embossed btn-primary"
                    style="width:230px;background-color:#19bb9b;">
            </form>
        </div>
    </div>

	<div class="wrapper" id="success-wrapper" style="display: none;">
		<div class="wrapper-content">
			<p>成功提交，你可以放心的等待了。</p>
            <p><a id="btn-register" class="btn btn btn-success" style="margin: 0 10px;" href="/register">注册</a></p>
            <p style="font-size: 10px;color: #16a085;">毕竟只能用一次，还是注册一下吧</p>
            <p><a id="btn-back" class="btn btn btn-success" style="margin: 0 10px;" href="#">点此返回</a></p>
		</div>
	</div>

    <div class="wrapper" id="failed-wrapper" style="display: none;">
        <div class="wrapper-content">
            <p>好像有什么不对劲的地方</p>
            <p><a id="btn-back" class="btn btn-danger" style="margin: 0 10px;" href="#">点此返回</a></p>
        </div>
    </div>

</div>
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
    $(function(){
        $("select").select2({dropdownCssClass: 'dropdown-inverse'});
        $('#try').click(function(){
            $('#top-wrapper').css('display','none');
            $('#red-wrapper').css('display','none');
            $('#try-wrapper').css('display','block');
        });
        $('#btn-cancel').click(function(){
            $('#top-wrapper').css('display','block');
            $('#red-wrapper').css('display','block');
            $('#try-wrapper').css('display','none');
        });
		$('#submit').click(function(){
			$('#try-wrapper').css('display','none');
			$('#success-wrapper').css('display','block');
			return true;
		});
		$('#btn-back').click(function(){
			$('#success-wrapper').css('display','none');
            $('#top-wrapper').css('display','block');
            $('#red-wrapper').css('display','block');
		});
    });
</script>
{% endblock %}

templates/my_print.html
{{uf.email}}
<div id="my-print" style="display: none;">
    <h4>我的打印<a id="print" data-toggle='modal' class="btn btn btn-danger" style="margin: 0 10px;" href="#upload-to-print">我要打印</a></h4>
    <ul class="list-group print-list" style="width: 640px;">

        {% for order in orders %}
        <li class="list-group-item">
            <h6 class="list-group-item-heading"><a href="{% url download_order_file order.id %}" target="_blank">{{ order.get_file_name }}</a></h6>
            上传时间：{{ order.time }} </br>
            状态：{{ order.get_status }}
        </li>        
        {% endfor %}
    </ul>
</div>

<div id="upload-to-print" class="modal fade in" style="display: none;">
    <h4>填写打印信息</h4>

    <form class="form-horizontal" role="form" method="POST"  enctype="multipart/form-data" action="/print_order" style="width: 700px;">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-lg-2">上传的文件</label>

            <div class="col-lg-5">
                <input type="file" id="print-file" name="file" class="btn btn-embossed btn-primary"
                       style="width: 270px;"/>
            </div>
        </div>

        <div class="form-group">
            <label for="radio" class="control-label col-lg-2">色彩选择</label>

            <div class="col-lg-5" title="彩印和黑白，你懂得" data-toggle="tooltip">
                <label class="radio" for="black-white">
                    <input type="radio" name="color" value="1" id="black-white" data-toggle="radio">
                    黑白
                </label>
                <label class="radio" for="colorful">
                    <input type="radio" name="color" value="0" id="colorful" data-toggle="radio">
                    彩印
                </label>
            </div>
        </div>

        <div class="form-group">
            <label for="radio" class="control-label col-lg-2">打印方式</label>

            <div class="col-lg-5">
                <label class="radio" for="free" title="免费打印会有广告嵌入" data-toggle="tooltip">
                    <input type="radio" name="method" value="1" id="free" data-toggle="radio">
                    免费打印
                </label>
                <label class="radio" for="paid" title="付费打印一切正常" data-toggle="tooltip">
                    <input type="radio" name="method" value="0" id="paid" data-toggle="radio">
                    付费打印
                </label>
            </div>
        </div>

        <div class="form-group">
            <label for="radio" class="control-label col-lg-2">备注</label>

            <div class="col-lg-5" title="有没有什么特殊要求？" data-toggle="tooltip">
                <input name="tel" id="tel" type="text" placeholder="还想交代点什么？"
                       class="form-control input-default txt-info"/>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-lg-4"></label>
            <input class="col-lg-1 btn btn-default btn-primary" type="submit" value="打印"/>
            <input class="col-lg-1 btn btn-default btn-primary" data-dismiss="modal" type="button" value="取消" style="margin-left: 20px;"/>
        </div>

    </form>
</div>

templates/register.html
{% extends 'base.html' %}

{% block custom_css %}
    <style type="text/css">
        .wrapper {
            text-align: center;
            color: #fff;
            background-color: #405564;
            height: 450px;
            margin: 20px auto 20px auto;
            width: 460px;
        }
        .register-wrapper {
            width: 250px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 30px;
        }
        .register-form input {
            background-color: #293a4a;
            margin: 10px 0 10px 0;
            width: 250px;
            color: #fff;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="wrapper">
        <div class="register-wrapper">
            <form class="form-group register-form" method="POST" action="/register">
                {% csrf_token %}
                <input type="text" name="email" placeholder="邮箱" class="form-control" />
                <input type="text" name="name" placeholder="用户名" class="form-control" />
                <input type="password" name="password" placeholder="密码" class="form-control" />
                <input type="text" name="phone_number" placeholder="电话号码" class="form-control" />

                <!-- Building select -->
                <select class="form-control select select-primary select-block mbl" id="build-select" name="building">
                    <option value="100">选择宿舍以便于我们配送</option>
                    {% for group in groups %}
                    <optgroup label="{{ group.name }}">
                        {% for building in group.building_set.all %}
                        <option value="{{ building.id }}">{{ building.name }}</option>
                        {% endfor %}
                    </optgroup>
                    {% endfor %}
                </select>

                <input type="submit" value="注册" class="btn btn-embossed btn-primary"
                    style="width:230px;background-color:#19bb9b;" />
            </form>
        </div>
    </div>
    <!-- /.wrapper-->
</div>
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript">
    $(function(){
        $("select").select2({dropdownCssClass: 'dropdown-inverse'});
    });
</script>
{% endblock %}

templates/user_info.html
<div id="user-info">
	<h4>个人信息</h4>

	<form class="form-horizontal" role="form" method="GET" action="/dashboard/update_profile" style="width: 700px;">
		<!-- Nick name form -->
		<div class="form-group">
			<label for="name" class="control-label col-lg-2">姓名</label>
			<div class="col-lg-5">
				<input name="name" id="name" type="text" placeholder="怎么称呼？" class="form-control input-default txt-info" value="{{ user_profile.name }}" />
			</div>
		</div>

		<div class="form-group">
			<label for="phone" class="control-label col-lg-2">电话</label>
			<div class="col-lg-5">
				<input name="phone" id="phone" type="text" placeholder="我们怎么联系你？" class="form-control input-default txt-info" value="{{ user_profile.phone_number }}" />
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-lg-2">学号</label>
			<div class="col-lg-5">
				<input name="student_number" id="number" type="text" placeholder="你的学号多少？" class="form-control input-default txt-info" value="{{ user_profile.number }}" />
			</div>
		</div>

		<!-- Building form -->
		<div class="form-group">
			<label for="build-select" class="control-label col-lg-2" >宿舍</label>
			<div class="col-lg-5">
				<select class="form-control select select-primary select-block mbl" id="build-select" name="building">
					<option value="100">选择宿舍以便于我们配送</option>
					{% for group in groups %}
					<optgroup label="{{ group.name }}">
						{% for building in group.building_set.all %}
						<option value="{{ building.id }}">{{ building.name }}</option>
						{% endfor %}
					</optgroup>
					{% endfor %}
				</select>
			</div>
		</div>

		<div class="form-group">
			<label for="radio" class="control-label col-lg-2">性别</label>
			<div class="col-lg-5">
				<label class="radio" for="girl">
					<input type="radio" name="gender" value="0" id="girl" data-toggle="radio">
					妹子
	            </label>
	            <label class="radio" for="boy">
					<input type="radio" name="gender" value="1" id="boy" data-toggle="radio">
					汉子
	            </label>
			</div>
		</div>

		<!-- Submit button -->
		<div class="form-group">
			<label class="control-label col-lg-5"></label>
			<input class="col-lg-1 btn btn-default btn-primary" type="submit" value="确认" />
		</div>
	</form>
</div>